// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl2zC_7VHimj3TloyM1tbotFE9nP6IUoE',
    appId: '1:347867110664:web:9f00e4768ee0674714e0bd',
    messagingSenderId: '347867110664',
    projectId: 'facebook-f9cae',
    authDomain: 'facebook-f9cae.firebaseapp.com',
    storageBucket: 'facebook-f9cae.firebasestorage.app',
    measurementId: 'G-3M23TSEVKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9BWF5AJXsW6XSWQHBOZi_DMLf6XaZQho',
    appId: '1:347867110664:android:8d1c202e52cb676214e0bd',
    messagingSenderId: '347867110664',
    projectId: 'facebook-f9cae',
    storageBucket: 'facebook-f9cae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJgotaOuWihelMVyq1DTCMHCf42JTIgb4',
    appId: '1:347867110664:ios:7beb05a893b14c7614e0bd',
    messagingSenderId: '347867110664',
    projectId: 'facebook-f9cae',
    storageBucket: 'facebook-f9cae.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJgotaOuWihelMVyq1DTCMHCf42JTIgb4',
    appId: '1:347867110664:ios:7beb05a893b14c7614e0bd',
    messagingSenderId: '347867110664',
    projectId: 'facebook-f9cae',
    storageBucket: 'facebook-f9cae.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl2zC_7VHimj3TloyM1tbotFE9nP6IUoE',
    appId: '1:347867110664:web:5e43b86a88d934e614e0bd',
    messagingSenderId: '347867110664',
    projectId: 'facebook-f9cae',
    authDomain: 'facebook-f9cae.firebaseapp.com',
    storageBucket: 'facebook-f9cae.firebasestorage.app',
    measurementId: 'G-5RN3D7TVR9',
  );
}
